/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative */

#ifndef _Included_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
#define _Included_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative
 * Method:    getColors
 * Signature: (III)[I
 */
JNIEXPORT jintArray JNICALL Java_com_android_systemui_statusbar_phone_BarBackgroundUpdaterNative_getColors
  (JNIEnv *, jclass, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
